# -*- coding: utf-8 -*-
"""Untitled120.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y9vevwfwBxH9VcSuL21h0tnUed-9l2AA
"""

! pip install streamlit

import streamlit as st
import pandas as pd
st.title('Uber pickups in NYC')